In [26]:
#Lets import pandas libraries
import pandas as pd

##### Pizza Place Sales

In [3]:
order_detail= pd.read_csv(r"C:\Users\MSI\Downloads\order_details.csv")

In [4]:
order_detail.head()

   order_details_id  order_id       pizza_id  quantity
0                 1         1     hawaiian_m         1
1                 2         2  classic_dlx_m         1
2                 3         2  five_cheese_l         1
3                 4         2    ital_supr_l         1
4                 5         2     mexicana_m         1

In [5]:
order=pd.read_csv(r"C:\Users\MSI\Downloads\orders.csv")

In [6]:
order.head()

   order_id        date      time
0         1  2015-01-01  11:38:36
1         2  2015-01-01  11:57:40
2         3  2015-01-01  12:12:28
3         4  2015-01-01  12:16:31
4         5  2015-01-01  12:21:30

In [7]:
pizza = pd.read_csv(r"C:\Users\MSI\Downloads\pizzas.csv")

In [8]:
pizza.head()

     pizza_id pizza_type_id size  price
0   bbq_ckn_s       bbq_ckn    S  12.75
1   bbq_ckn_m       bbq_ckn    M  16.75
2   bbq_ckn_l       bbq_ckn    L  20.75
3  cali_ckn_s      cali_ckn    S  12.75
4  cali_ckn_m      cali_ckn    M  16.75

In [9]:
pizza_types = pd.read_csv(r"C:\Users\MSI\Downloads\pizza_types.csv", encoding= "cp1252")

In [10]:
pizza_types.head()

,pizza_type_id,name,category,ingredients
0,bbq_ckn,The Barbecue Chicken Pizza,Chicken,"Barbecued Chicken, Red Peppers, Green Peppers,..."
1,cali_ckn,The California Chicken Pizza,Chicken,"Chicken, Artichoke, Spinach, Garlic, Jalapeno ..."
2,ckn_alfredo,The Chicken Alfredo Pizza,Chicken,"Chicken, Red Onions, Red Peppers, Mushrooms, A..."
3,ckn_pesto,The Chicken Pesto Pizza,Chicken,"Chicken, Tomatoes, Red Peppers, Spinach, Garli..."
4,southw_ckn,The Southwest Chicken Pizza,Chicken,"Chicken, Tomatoes, Red Peppers, Red Onions, Ja..."

In [15]:
#Merge dataset (To join Order_detail wirh pizza)
detail_pizza = pd.merge(order_detail,pizza, on= "pizza_id", how= "left")

In [16]:
detail_pizza

,order_details_id,order_id,pizza_id,quantity,pizza_type_id,size,price
0,1,1,hawaiian_m,1,hawaiian,M,13.25
1,2,2,classic_dlx_m,1,classic_dlx,M,16.00
2,3,2,five_cheese_l,1,five_cheese,L,18.50
3,4,2,ital_supr_l,1,ital_supr,L,20.75
4,5,2,mexicana_m,1,mexicana,M,16.00
...,...,...,...,...,...,...,...
48615,48616,21348,ckn_alfredo_m,1,ckn_alfredo,M,16.75
48616,48617,21348,four_cheese_l,1,four_cheese,L,17.95
48617,48618,21348,napolitana_s,1,napolitana,S,12.00
48618,48619,21349,mexicana_l,1,mexicana,L,20.25
48619,48620,21350,bbq_ckn_s,1,bbq_ckn,S,12.75

In [22]:
#join with pizza_types(to grt categoru and ingredents)

detail_full= pd.merge(detail_pizza,pizza_types,on="pizza_type_id")

In [23]:
detail_full

,order_details_id,order_id,pizza_id,quantity,pizza_type_id,size,price,name,category,ingredients
0,1,1,hawaiian_m,1,hawaiian,M,13.25,The Hawaiian Pizza,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese"
1,2,2,classic_dlx_m,1,classic_dlx,M,16.00,The Classic Deluxe Pizza,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,..."
2,3,2,five_cheese_l,1,five_cheese,L,18.50,The Five Cheese Pizza,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go..."
3,4,2,ital_supr_l,1,ital_supr,L,20.75,The Italian Supreme Pizza,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni..."
4,5,2,mexicana_m,1,mexicana,M,16.00,The Mexicana Pizza,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O..."
...,...,...,...,...,...,...,...,...,...,...
48615,48616,21348,ckn_alfredo_m,1,ckn_alfredo,M,16.75,The Chicken Alfredo Pizza,Chicken,"Chicken, Red Onions, Red Peppers, Mushrooms, A..."
48616,48617,21348,four_cheese_l,1,four_cheese,L,17.95,The Four Cheese Pizza,Veggie,"Ricotta Cheese, Gorgonzola Piccante Cheese, Mo..."
48617,48618,21348,napolitana_s,1,napolitana,S,12.00,The Napolitana Pizza,Classic,"Tomatoes, Anchovies, Green Olives, Red Onions,..."
48618,48619,21349,mexicana_l,1,mexicana,L,20.25,The Mexicana Pizza,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O..."
48619,48620,21350,bbq_ckn_s,1,bbq_ckn,S,12.75,The Barbecue Chicken Pizza,Chicken,"Barbecued Chicken, Red Peppers, Green Peppers,..."

In [24]:
#Joining With Orders, to get the date and time of the transations of each order

final_df=pd.merge(detail_full,order,on = "order_id")

In [25]:
final_df

,order_details_id,order_id,pizza_id,quantity,pizza_type_id,size,price,name,category,ingredients,date,time
0,1,1,hawaiian_m,1,hawaiian,M,13.25,The Hawaiian Pizza,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",2015-01-01,11:38:36
1,2,2,classic_dlx_m,1,classic_dlx,M,16.00,The Classic Deluxe Pizza,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",2015-01-01,11:57:40
2,3,2,five_cheese_l,1,five_cheese,L,18.50,The Five Cheese Pizza,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",2015-01-01,11:57:40
3,4,2,ital_supr_l,1,ital_supr,L,20.75,The Italian Supreme Pizza,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",2015-01-01,11:57:40
4,5,2,mexicana_m,1,mexicana,M,16.00,The Mexicana Pizza,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",2015-01-01,11:57:40
...,...,...,...,...,...,...,...,...,...,...,...,...
48615,48616,21348,ckn_alfredo_m,1,ckn_alfredo,M,16.75,The Chicken Alfredo Pizza,Chicken,"Chicken, Red Onions, Red Peppers, Mushrooms, A...",2015-12-31,21:23:10
48616,48617,21348,four_cheese_l,1,four_cheese,L,17.95,The Four Cheese Pizza,Veggie,"Ricotta Cheese, Gorgonzola Piccante Cheese, Mo...",2015-12-31,21:23:10
48617,48618,21348,napolitana_s,1,napolitana,S,12.00,The Napolitana Pizza,Classic,"Tomatoes, Anchovies, Green Olives, Red Onions,...",2015-12-31,21:23:10
48618,48619,21349,mexicana_l,1,mexicana,L,20.25,The Mexicana Pizza,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",2015-12-31,22:09:54
48619,48620,21350,bbq_ckn_s,1,bbq_ckn,S,12.75,The Barbecue Chicken Pizza,Chicken,"Barbecued Chicken, Red Peppers, Green Peppers,...",2015-12-31,23:02:05

In [27]:
final_df.head()

,order_details_id,order_id,pizza_id,quantity,pizza_type_id,size,price,name,category,ingredients,date,time
0,1,1,hawaiian_m,1,hawaiian,M,13.25,The Hawaiian Pizza,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",2015-01-01,11:38:36
1,2,2,classic_dlx_m,1,classic_dlx,M,16.00,The Classic Deluxe Pizza,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",2015-01-01,11:57:40
2,3,2,five_cheese_l,1,five_cheese,L,18.50,The Five Cheese Pizza,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",2015-01-01,11:57:40
3,4,2,ital_supr_l,1,ital_supr,L,20.75,The Italian Supreme Pizza,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",2015-01-01,11:57:40
4,5,2,mexicana_m,1,mexicana,M,16.00,The Mexicana Pizza,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",2015-01-01,11:57:40

In [29]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48620 entries, 0 to 48619
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_details_id  48620 non-null  int64
 1   order_id          48620 non-null  int64
 2   pizza_id          48620 non-null  object
 3   quantity          48620 non-null  int64
 4   pizza_type_id     48620 non-null  object
 5   size              48620 non-null  object
 6   price             48620 non-null  float64
 7   name              48620 non-null  object
 8   category          48620 non-null  object
 9   ingredients       48620 non-null  object
 10  date              48620 non-null  object
 11  time              48620 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.5+ MB

In [76]:
#Cleaning Data is neccessary to put Date and Time in proper Dtype
#Convert date and time column to datetime format

order["date"]= pd.to_datetime(order["date"],errors= 'coerce')

In [79]:
order["datetime"]=pd.to_datetime(order['date'].astype(str)+" "+ order["time"].astype(str), errors= "coerce")

In [38]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48620 entries, 0 to 48619
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_details_id  48620 non-null  int64
 1   order_id          48620 non-null  int64
 2   pizza_id          48620 non-null  object
 3   quantity          48620 non-null  int64
 4   pizza_type_id     48620 non-null  object
 5   size              48620 non-null  object
 6   price             48620 non-null  float64
 7   name              48620 non-null  object
 8   category          48620 non-null  object
 9   ingredients       48620 non-null  object
 10  date              48620 non-null  object
 11  time              48620 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.5+ MB

In [40]:
final_df

,order_details_id,order_id,pizza_id,quantity,pizza_type_id,size,price,name,category,ingredients,date,time
0,1,1,hawaiian_m,1,hawaiian,M,13.25,The Hawaiian Pizza,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",2015-01-01,11:38:36
1,2,2,classic_dlx_m,1,classic_dlx,M,16.00,The Classic Deluxe Pizza,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",2015-01-01,11:57:40
2,3,2,five_cheese_l,1,five_cheese,L,18.50,The Five Cheese Pizza,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",2015-01-01,11:57:40
3,4,2,ital_supr_l,1,ital_supr,L,20.75,The Italian Supreme Pizza,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",2015-01-01,11:57:40
4,5,2,mexicana_m,1,mexicana,M,16.00,The Mexicana Pizza,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",2015-01-01,11:57:40
...,...,...,...,...,...,...,...,...,...,...,...,...
48615,48616,21348,ckn_alfredo_m,1,ckn_alfredo,M,16.75,The Chicken Alfredo Pizza,Chicken,"Chicken, Red Onions, Red Peppers, Mushrooms, A...",2015-12-31,21:23:10
48616,48617,21348,four_cheese_l,1,four_cheese,L,17.95,The Four Cheese Pizza,Veggie,"Ricotta Cheese, Gorgonzola Piccante Cheese, Mo...",2015-12-31,21:23:10
48617,48618,21348,napolitana_s,1,napolitana,S,12.00,The Napolitana Pizza,Classic,"Tomatoes, Anchovies, Green Olives, Red Onions,...",2015-12-31,21:23:10
48618,48619,21349,mexicana_l,1,mexicana,L,20.25,The Mexicana Pizza,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",2015-12-31,22:09:54
48619,48620,21350,bbq_ckn_s,1,bbq_ckn,S,12.75,The Barbecue Chicken Pizza,Chicken,"Barbecued Chicken, Red Peppers, Green Peppers,...",2015-12-31,23:02:05

In [44]:
order.info()  #date and time now in the correct datetime format

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21350 entries, 0 to 21349
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   order_id  21350 non-null  int64
 1   date      21350 non-null  datetime64[ns]
 2   time      21350 non-null  object
 3   datetime  21350 non-null  datetime64[ns]
dtypes: datetime64[ns](2), int64(1), object(1)
memory usage: 667.3+ KB

In [45]:
order.head()

   order_id       date      time            datetime
0         1 2015-01-01  11:38:36 2015-01-01 11:38:36
1         2 2015-01-01  11:57:40 2015-01-01 11:57:40
2         3 2015-01-01  12:12:28 2015-01-01 12:12:28
3         4 2015-01-01  12:16:31 2015-01-01 12:16:31
4         5 2015-01-01  12:21:30 2015-01-01 12:21:30

##### Analysis sales and revenue of Pizza Place sales

##### 1. Total Revenue/Sales

In [46]:
#Revenue = Quantity * price

total_revenue = (final_df["quantity"]*final_df["price"]).sum()

In [47]:
total_revenue

np.float64(817860.0499999999)

In [48]:
print("total_revenue: ",total_revenue)

total_revenue:  817860.0499999999

##### 2. Total Quantity Sold

In [49]:
#additions of all the quantity sold

total_quantity_sold= final_df["quantity"].sum()

In [50]:
total_quantity_sold

np.int64(49574)

In [51]:
print("total_quantity_sold :", total_quantity_sold)

total_quantity_sold : 49574

##### 3. Total Orders

In [52]:
total_orders= final_df["order_id"].nunique()

In [53]:
total_orders

21350

##### 4. Pizza types sold

In [64]:
pizza_type_count= final_df['pizza_type_id'].nunique()

In [65]:
pizza_type_count

32

##### 5. Average Price of Pizzas

In [66]:
average_price= final_df["price"].mean()

In [67]:
print("Average Price of Pizzas: ", average_price)

Average Price of Pizzas:  16.494132044426163

##### 6. Peak Hours of Sales

In [83]:
#Etract the hours from Time

print(final_df.columns)

final_df["date"]= pd.to_datetime(final_df["date"].astype(str)+ ' ' + final_df["time"].astype(str), errors="coerce")

Index(['order_details_id', 'order_id', 'pizza_id', 'quantity', 'pizza_type_id',
       'size', 'price', 'name', 'category', 'ingredients', 'date', 'time'],
      dtype='object')

In [86]:
print(final_df.columns.tolist())

['order_details_id', 'order_id', 'pizza_id', 'quantity', 'pizza_type_id', 'size', 'price', 'name', 'category', 'ingredients', 'date', 'time']

In [87]:
date_col= [col for col in final_df.columns if col.lower() == "date"][0]
time_col= [col for col in final_df.columns if col.lower() == "time"][0]

In [88]:
final_df["datetime"]= pd.to_datetime(final_df[date_col].astype(str)+ " " + final_df[time_col].astype(str),errors="coerce")

C:\Users\MSI\AppData\Local\Temp\ipykernel_1564\1074994439.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  final_df["datetime"]= pd.to_datetime(final_df[date_col].astype(str)+ " " + final_df[time_col].astype(str),errors="coerce")

In [89]:
final_df["hour"]= final_df["datetime"].dt.hour

In [90]:
print(final_df[["datetime","hour"]].head())

             datetime  hour
0 2015-01-01 11:38:36    11
1 2015-01-01 11:57:40    11
2 2015-01-01 11:57:40    11
3 2015-01-01 11:57:40    11
4 2015-01-01 11:57:40    11

In [91]:
# Group by hour
orders_by_hour= final_df.groupby("hour")["order_id"].nunique()

In [92]:
orders_by_hour

hour
9        1
10       8
11    1231
12    2520
13    2455
14    1472
15    1468
16    1920
17    2336
18    2399
19    2009
20    1642
21    1198
22     663
23      28
Name: order_id, dtype: int64

In [93]:
#Let sort to get the peak hours

peak_hours= orders_by_hour.sort_values(ascending=False)

In [96]:
print("Peak Hours of Sales: \n", peak_hours.head(10))

Peak Hours of Sales:
 hour
12    2520
13    2455
18    2399
17    2336
19    2009
16    1920
20    1642
14    1472
15    1468
11    1231
Name: order_id, dtype: int64

##### 7. Find the Total sales per weekdays

###### The below is the breakdown of sales per each days

In [100]:
final_df["weekday"]= final_df["datetime"].dt.day_name()

In [101]:
sales_per_weekday =(final_df["quantity"]*final_df["price"]).groupby(final_df["weekday"]).sum()

In [104]:
print(sales_per_weekday)  #to indicate each sale perday of the week

weekday
Friday       136073.90
Monday       107329.55
Saturday     123182.40
Sunday        99203.50
Thursday     123528.50
Tuesday      114133.80
Wednesday    114408.40
dtype: float64

###### To Calculate the Best day of the week

In [105]:
best_day = sales_per_weekday.idxmax()
best_sales = sales_per_weekday.max()
print("Best Sales Day: ", best_day, "With Sales Of", best_sales)

Best Sales Day:  Friday With Sales Of 136073.9

In [107]:
best_day = sales_per_weekday.idxmax()
print("Best Day: ", best_day, "With Sales On", best_day)

Best Day:  Friday With Sales On Friday

###### 8. Top 5 Bestselling Pizzas

In [109]:
#Let sum up all quantity sold for each pizza type

top5_pizzas = final_df.groupby("pizza_type_id")["quantity"].sum().sort_values(ascending= False).head(5)
print("Top 5 Bestselling Pizzas: \n", top5_pizzas)

Top 5 Bestselling Pizzas:
 pizza_type_id
classic_dlx    2453
bbq_ckn        2432
hawaiian       2422
pepperoni      2418
thai_ckn       2371
Name: quantity, dtype: int64

In [110]:

top5_pizzas_name = final_df.groupby("name")["quantity"].sum().sort_values(ascending= False).head(5)
print("Top 5 Bestselling Pizzas(With Names): \n", top5_pizzas_name)

Top 5 Bestselling Pizzas(With Names):
 name
The Classic Deluxe Pizza      2453
The Barbecue Chicken Pizza    2432
The Hawaiian Pizza            2422
The Pepperoni Pizza           2418
The Thai Chicken Pizza        2371
Name: quantity, dtype: int64

##### 9. Sales By Months

In [111]:
#Let extract the Month

final_df["Month"] = final_df["datetime"].dt.month_name()

In [112]:
# Let Calculate sales per Months

sales_by_month = (final_df["quantity"]*final_df["price"]).groupby(final_df["Month"]).sum()
print(sales_by_month)

Month
April        68736.80
August       68278.25
December     64701.15
February     65159.60
January      69793.30
July         72557.90
June         68230.20
March        70397.10
May          71402.75
November     70395.35
October      64027.60
September    64180.05
dtype: float64

#Let identify the strongest month

best_month= sales_by_month.idxmax()
best_sales= sales_by_month.max()
print("Best Month: ", best_month, "With Sales of",best_sales)

###### 10. Underperming Pizzas on the Menu

In [118]:
#Let group by pizza type
underperforming= final_df.groupby("pizza_type_id")["quantity"].sum().sort_values().head(10)
print("Lowest Selling Pizzas: \n", underperforming)

Lowest Selling Pizzas:
 pizza_type_id
brie_carre      490
mediterraneo    934
calabrese       937
spinach_supr    950
soppressata     961
spin_pesto      970
ckn_pesto       973
ital_veggie     981
ckn_alfredo     987
green_garden    997
Name: quantity, dtype: int64

In [120]:
underperforming_name= final_df.groupby("name")["quantity"].sum().sort_values().head(5)
print("Lowest Selling Pizzas(with names): \n", underperforming_name)

Lowest Selling Pizzas(with names):
 name
The Brie Carre Pizza         490
The Mediterranean Pizza      934
The Calabrese Pizza          937
The Spinach Supreme Pizza    950
The Soppressata Pizza        961
Name: quantity, dtype: int64

##### End of Task3